---
- hosts: all
  tasks:
  - name: Register as user (joe_user) with password (somepass) and auto-subscribe to available content.
    redhat_subscription:
      state: present
      username: "jclaretm@redhat.com"
      password: "" # PASSWORD IN VAULT FILE
      auto_attach: true
  - name: Enable a RHSM repository
    rhsm_repository:
      name: rhel-7-server-rpms
