- name: Perform an OpenShift login
  hosts: local
  gather_facts: false
  tasks:
    - name: openShift login
      args:
        warn: false
      command: curl -X GET -H "Authorization\":\" Bearer {{ctti_ocp_token}}" {{ctti_ocp_url}}/oapi/v1 --insecure
    - name: sleep for 3 seconds and continue with play
      wait_for: timeout=3
