---
- hosts: webservers
  gather_facts: false
  tasks:
  - name: Check if port is up
    wait_for:
      port: 80
      timeout: 10
      delay: 10
      timeout: 900
      msg: "Port 80 is accessible, application is already installed and running"
    register: service_status

  - name: Check Results
    debug:
      var: service_status
