- name: Sales Application Stock Processor Service
  hosts: localhost
  gather_facts: false
  tasks:
    - name: openShift sales-stock-processor
      args:
        warn: false
      command: curl -X POST -H "Content-Type\":\" application/json" -H "Authorization\":\" Bearer {{ctti_ocp_token}}" -k {{ctti_ocp_url}}/apis/build.openshift.io/v1/namespaces/cicd-ocpadmin/buildconfigs/sales-deploy-stock-processor-pipeline/webhooks/secretvalue2/generic
    - name: sleep for 360 seconds and continue with play
      wait_for: timeout=360
      delegate_to: localhost
