---
#
# This playbook executes an OpenShift Build Config.
#
# parameters:
# * user
# * api_url
# * api_key
# * sec_token
# * project_name
# * build_config_name

- name: Executes a build config
  hosts: all
  gather_facts: false
  tasks:

    - name: Executes a build config
      openshift_raw:
        state: present
        host: "{{api_url}}"
        username: "{{user}}"
        api_key: "{{api_key}}"
        definition:
          apiVersion: v1
          kind: BuildConfig
          metadata:
           name: "{{app_name}}"
           namespace: "{{project_name}}"
          spec:
           output:
             to:
               kind: ImageStreamTag
               name: "{{app_name}}:latest"
           source:
             git:
               uri: "{{app_git_url}}"
             type: Git
           strategy:
             sourceStrategy:
               from:
                 kind: ImageStreamTag
                 name: "{{src_image_name}}:latest"
                 namespace: openshift
             type: Source
             